# Generated by Django 5.0.3 on 2024-03-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.TextField(verbose_name='State')),
                ('County', models.TextField(verbose_name='County')),
                ('Under5yrsPopulation_total', models.TextField(verbose_name='Under5yrsPopulation_total')),
                ('Under5yrsPopulation_female', models.TextField(verbose_name='Under5yrsPopulation_female')),
                ('t5to17yrsPopulation_total', models.TextField(verbose_name='t5to17yrsPopulation_total')),
                ('t5to17yrs_Female', models.TextField(verbose_name='t5to17yrs_Female')),
                ('t18to24yearsPopulation', models.TextField(verbose_name='t18to24yearsPopulation')),
                ('t18to24yrs_Female', models.TextField(verbose_name='t18to24yrs_Female')),
                ('t25to34yrs_Population', models.TextField(verbose_name='t25to34yrs_Population')),
                ('t25to34years_Female', models.TextField(verbose_name='t25to34years_Female')),
                ('t35to44yrs_Population', models.TextField(verbose_name='t35to44yrs_Population')),
                ('t35to44yrs_Female', models.TextField(verbose_name='t35to44yrs_Female')),
                ('t45to64yrs_Population', models.TextField(verbose_name='t45to64yrs_Population')),
                ('t45to64yrs_Female', models.TextField(verbose_name='t45to64yrs_Female')),
                ('t65to84years_Population', models.TextField(verbose_name='t65to84years_Population')),
                ('t65to84yrs_Female', models.TextField(verbose_name='t65to84yrs_Female')),
                ('t85to99yrs_Population', models.TextField(verbose_name='t85to99yrs_Population')),
                ('t85to99yrs_Female', models.TextField(verbose_name='t85to99yrs_Female')),
                ('t100_years_and_Over_Population', models.TextField(verbose_name='t100_years_and_Over_Population')),
                ('t100yrs_and_over_Female', models.TextField(verbose_name='t100yrs_and_over_Female')),
            ],
            options={
                'verbose_name': 'Population',
                'verbose_name_plural': 'Population',
            },
        ),
    ]
